-- 作品紹介の任意項目。既存の作品・上映回・予約は変更しない。
ALTER TABLE movies
    ADD COLUMN IF NOT EXISTS director VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cast_members VARCHAR(4000) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS distributor VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS official_site_url VARCHAR(2000) NOT NULL DEFAULT '';
